name: Merge any mian branch to preview
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Merge master back to preview
        run: |
          git fetch --unshallow
          git checkout preview
          git pull
          git merge master
          git push
