name: Sync to Preview Branch

on:
  push:
    branches:
      - main

jobs:
  sync-to-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Configure user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      
      - name: Sync main to preview
        run: |
          git fetch origin preview
          git checkout preview
          git merge --ff-only origin/main
          git push origin preview
