name: Sync to Preview Branch

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-to-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: 'main'
      
      - name: Push changes to preview branch
        run: |
          git config pull.rebase true
          git checkout -b preview
          git pull origin preview
          git merge main --no-edit
          git push origin preview
